CREATE DATABASE LESSON1;

USE LESSON1;


CREATE TABLE STUDENT(
STUDENT_ID   NUMERIC(20) NOT NULL,
FIRST_NAME   VARCHAR(20) NOT NULL,
LAST_NAME    VARCHAR(200) NOT NULL,
DEPARTMENT   VARCHAR(30),
PRIMARY KEY (STUDENT_ID));


CREATE TABLE DEPARTMENT(
DEPARTMENT_ID  NUMERIC(20) NOT NULL,
DEPARTMENT_NAME    VARCHAR(200) NOT NULL,
PRIMARY KEY (DEPARTMENT_ID));

CREATE TABLE COURSES(
COURSE_ID     NUMERIC(20) NOT NULL,
COURSE_NAME   VARCHAR(50) NOT NULL,
DEPARTMENT_ID    NUMERIC(20) NOT NULL,
PRIMARY KEY (COURSE_ID),
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID));


CREATE TABLE GRADES(
GRADE_ID     NUMERIC(20) NOT NULL,
STUDENT_ID   NUMERIC(20) NOT NULL,
COURSE_NAME   VARCHAR(50) NOT NULL,
FINAL_GRADE   NUMERIC(5,2) NOT NULL,
PRIMARY KEY (GRADE_ID),
FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID));