USE Jepil200494772;

CREATE TABLE genres
(genreId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL);

SELECT * FROM genres;


CREATE TABLE movies (
movieId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
rating VARCHAR(10),
releaseYear INT NOT NULL,
image VARCHAR(100),
genreId INT NOT NULL,
FOREIGN KEY (genreId) REFERENCES genres(genreId)
);

ALTER TABLE movies AUTO_INCREMENT 1000;

SELECT * FROM movies;